name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Python 3.x on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-2016]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      if: startsWith(matrix.os, 'ubuntu')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v1
      if: startsWith(matrix.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v1
      if: startsWith(matrix.os, 'windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -e .

    - name: Build manylinux Python wheels
      if: startsWith(matrix.os, 'ubuntu')
      uses: RalfG/python-wheels-manylinux-build@v0.2.2
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        build-requirements: '-e .'  # pip args

    - name: Publish manylinux Python wheels
      if: startsWith(matrix.os, 'ubuntu')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*-manylinux*.whl

    - name: Build and publish wheel
      if: "! startsWith(matrix.os, 'ubuntu')"
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*.whl

    - name: Build standalone executable
      if: startsWith(matrix.os, 'windows')
      run: |
        pip install --upgrade pyinstaller
        pyinstaller nmlc.spec
        $version = python setup.py --version
        echo "::set-output name=version::$version"
      id: nml_version

    - name: Archive executable
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v1
      with:
        name: nml-${{ steps.nml_version.outputs.version }}-win64
        path: dist/nmlc.exe

    # TODO: Remove this and/or replace with something more specific
    - name: Archive distribution
      uses: actions/upload-artifact@v1
      with:
        name: nml-build-artifacts-${{ matrix.os }}
        path: dist
